name: Android CI

on:
  workflow_dispatch:
  push:
    branches:
      - master
    paths:
      - 'hitomi/**'

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    
    - name: Decode Keystore
      uses: timheuer/base64-to-file@v1.1
      with:
        fileName: 'keystore.jks'
        fileDir: '/tmp/'
        encodedString: ${{ secrets.KEYSTORE }}
      
    - name: Check if key exists
      run: test -e /tmp/keystore.jks
    
    - name: Build with Gradle
      run: ./gradlew hitomi:assembleRelease
      env:
        SIGNING_KEY_ALIAS: ${{ secrets.SIGNING_KEY_ALIAS }}
        SIGNING_KEY_PASSWORD: ${{ secrets.SIGNING_KEY_PASSWORD }}
        SIGNING_STORE_PASSWORD: ${{ secrets.SIGNING_STORE_PASSWORD }}
    
    - name: Release
      uses: softprops/action-gh-release@v1
      with:
        body_path: 'hitomi/build/outputs/apk/release/output-metadata.json'
        files: 'hitomi/build/outputs/apk/release/hitomi-release.apk'
